# Generated by Django 3.1.4 on 2021-01-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('application_form_eng', models.FileField(upload_to='')),
                ('application_form_kor', models.FileField(upload_to='')),
                ('application_collection_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
