# Generated by Django 3.1.4 on 2021-01-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiting_term', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('application_form_eng', models.FileField(upload_to='')),
                ('application_form_kor', models.FileField(upload_to='')),
                ('application_collection_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
