# Generated by Django 3.1.4 on 2021-01-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210110_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruiting',
            new_name='RecruitingBanner',
        ),
    ]
