# Generated by Django 3.1.4 on 2021-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210110_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='recruitingbanner',
            name='application_form_eng',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='recruitingbanner',
            name='application_form_kor',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
