# Generated by Django 3.1.4 on 2021-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_logo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitingbanner',
            name='brochure',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='recruitingbanner',
            name='application_form_eng',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='recruitingbanner',
            name='application_form_kor',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
