# Generated by Django 3.1.4 on 2021-01-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_keyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='description',
            field=models.TextField(),
        ),
    ]
