# Generated by Django 3.1.4 on 2021-01-11 14:11

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description_1', models.CharField(max_length=50)),
                ('description_2', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('greeting', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
