# Generated by Django 3.1.4 on 2021-01-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210111_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
